### ISSUE TITLE
Could not import

### ISSUE THREAD

**Issue by DIGIX666** [gnolang/gnopls-old#1]
<img width="1011" alt="SCR-20240530-rbgv" src="https://github.com/gnolang/gnopls/assets/90353329/5cf8e9d3-80ea-48e7-a017-4afc0b15e0ba">

I installed `gnopls` but it shows errors on imports even though it’s the correct method. Is this a known issue that is normal or I forgot a step ?

cc @harry-hov

**Comment by harry-hov** [comment]
Can you please check if `GNOROOT` is set globally?
```
echo $GNOROOT
```

`GNOROOT` => `path/to/gno/clone`

If not, you can do one of the following:
1. Update it in the vscode extension setting (if using vscode extension)
    <img width="1236" alt="Screenshot 2024-05-31 at 2 58 18 AM" src="https://github.com/gnolang/gnopls/assets/37576387/d8eba1d3-eaf6-4015-9fd2-11ee84c7088d">

2. Or, you can set `GNOROOT` environment variable globally (recommended if using `gnopls` with some other editor)

--

Edit: Restart your editor after setting `GNOROOT`!

**Comment by DIGIX666** [comment]
Thanks  @harry-hov , I no longer have the problem :)
